# @name get-all-books
GET http://localhost:3000/books

###

# @name get-book-by-id
GET http://localhost:3000/books/65a54448d4828d24d792f34e

###

# @name create-book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Harry Potter",
  "author": "J. K. Rowling",
  "publishYear": 2001
}

###

# @name update-book
PUT http://localhost:3000/books/65a54448d4828d24d792f34e
Content-Type: application/json

{
  "title": "Harry Potter 1",
  "author": "J. K. Rowling",
  "publishYear": 2001
}

###

# @name delete-book
DELETE http://localhost:3000/books/65a58fd0a23af6935933ffff
