# @name get-all-books
GET http://localhost:3000/books

###

# @name get-book-by-id
GET http://localhost:3000/books/65a54448d4828d24d792f34e

###

# @name create-book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Harry Potter",
  "author": "J. K. Rowling",
  "publishYear": 2001
}
